name: Deploy

on: 
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{secrets.HOST}}
        username: ${{ secrets.USERNAME}}
        key: ${{secrets.SSH}}
        password: ${{secrets.PASSWORD}}
        script: |
          cd ./training-ground/VACA-Ecommerce/
          git pull origin main
          cd ./client
          npm -v
          npm install --force
          npm run build
          cp -r ./build ../server/
          cd ../server
          npm install --omit-dev

          
          

            
            

